### ISSUE TITLE
2.1.25: all resolution commands fail with NoSuchMethodError — released jar bundles a mismatched cats

### ISSUE THREAD

**Issue by blandflakes** [coursier/coursier#3865]
# Steps to reproduce

curl -fLo coursier.jar https://github.com/coursier/coursier/releases/download/v2.1.25/coursier.jar
java -jar coursier.jar fetch foo:bar:1.0

## Observed Behavior

Exception in thread "main" java.lang.NoSuchMethodError: 'cats.Align cats.implicits$.catsStdInstancesForList()'
	at coursier.cli.options.CacheOptions.params(CacheOptions.scala:162)
	at coursier.cli.options.CacheOptions.params(CacheOptions.scala:92)
	at coursier.cli.resolve.SharedResolveParams$.apply(SharedResolveParams.scala:32)
	at coursier.cli.fetch.FetchParams$.apply(FetchParams.scala:42)
	at coursier.cli.fetch.Fetch$.run(Fetch.scala:96)
This happens during argument parsing, before any network access. launch and resolve fail with the same error via their own *Params$.apply frames. --help and version still work, so the jar loads fine.

Seems to be independent of jdk version

**Comment by blandflakes** [comment]
Correction: not specific to coursier.jar. The coursier bootstrap launcher from the same release fails identically, so the mismatch is in the JVM-side dependency set rather than the assembly. The native cs launcher is unaffected — cs fetch/cs launch work fine on 2.1.25.

**Comment by Gedochao** [comment]
Blocked by this in both Scala 3 compiler and Scala CLI.
