### ISSUE TITLE
`aarch64` not available in certain releases

### ISSUE THREAD

**Issue by xRuiAlves** [coursier/coursier#2711]
I've noticed that `aarch64` files are not available in a few releases. _E.g._:
- [v2.1.0](https://github.com/coursier/coursier/releases/tag/v2.1.0)
- [v2.1.0-RC6](https://github.com/coursier/coursier/releases/tag/v2.1.0-RC6)
- [v2.1.0-RC5](https://github.com/coursier/coursier/releases/tag/v2.1.0-RC5)

While in most others it is:
- [v2.1.0-RC4](https://github.com/coursier/coursier/releases/tag/v2.1.0-RC4) - https://github.com/coursier/coursier/releases/download/v2.1.0-RC4/cs-aarch64-pc-linux.gz
- [v2.0.16](https://github.com/coursier/coursier/releases/tag/v2.0.16) - https://github.com/coursier/coursier/releases/download/v2.0.16/cs-aarch64-pc-linux

Would it be possible to make `aarch64` files available for all released versions?

**Comment by mkurz** [comment]
Running Linux aarch64.

I have scala-cli installed via sdkman:
```sh
$ sdk list scalacli
================================================================================
Available Scalacli Versions
================================================================================
 > * 0.2.1                                                                      
     0.2.0                                                                      
   * 0.1.20                                                                     

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================

```
Latest 0.2.1 doesn't work:
```sh
$ scala-cli
Exception in thread "main" java.lang.NoClassDefFoundError: com.oracle.svm.core.JavaMainWrapper
        at scala.cli.internal.Argv0.get(Argv0.scala:16)
        at scala.cli.ScalaCli$.<clinit>(ScalaCli.scala:28)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
```

It was working with 0.1.20 however (but also not with 0.2.0.

**Comment by julienrf** [comment]
@mkurz isn’t that related to scala-cli instead of coursier?

**Comment by mkurz** [comment]
Oopsss sorry, seems I had to many tabs open and posting in the wrong issue. Sorry!

**Comment by julienrf** [comment]
The binaries for aarch64 and release 2.1.0 are now available in the repo linked by @alexarchambault.

**Comment by xRuiAlves** [comment]
Cool, thanks folks! 👍
